### ISSUE TITLE
adding unit on result?

### ISSUE THREAD

**Issue by badtant** [shauns/postcss-math#21]
Hi, I have a mixin that takes two numbers and calculates percentage between them. I then want to add a % unit to the result. Any ideas on how to do that?

```
@define-mixin percentage $width, $height {
        height: resolve(($height / $width) * 100);
}
```

I can do this:
`height: resolve(($height / $width) * 100)%;`
but I then have stylelint 
`Expected whitespace after ")"   function-whitespace-after`
that will add a spece before % which isn't what i want.

Any ideas on how to get this working without disabling stylelint?

**Comment by pqt** [comment]
Stylelint is specifically saying this is not allowed where it's needed.

Your best bet (and what I do personally) is disable it just for the one line.

`/* stylelint-disable-next-line function-whitespace-after */` should go right above your property.

This would look like

```css
@define-mixin percentage $width, $height {
  /* stylelint-disable-next-line function-whitespace-after */
  height: resolve(($height / $width) * 100)%;
}
```

Alternatively though, I don't see why you couldn't do something to this effect, this is untested but AFAIK this should work.
```css
@define-mixin percentage $width, $height {
  height: resolve(($height / $width) * 100%);
}
```
