### ISSUE TITLE
Update messed up output

### ISSUE THREAD

**Issue by Dylan-Chapman** [shauns/postcss-math#8]
Before the most recent  update:

``` css
.test {
    test: resolve( floor( 12 / 5 ) );
}
```

Would compile to:

``` css
.test {
    test: 2;
}
```

After the update, it compiles to:

``` css
.test {
    test: 2 12/5;
}
```

I'm assuming this isn't intended behavior.
